import esbuild from 'esbuild';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProduction = process.argv.includes('production');

esbuild.build({
  entryPoints: ['main.ts'],
  bundle: true,
  external: ['obsidian'],
  format: 'cjs',
  target: 'es2019',
  outfile: 'main.js',
  sourcemap: isProduction ? false : 'inline',
  treeShaking: true,
  minify: isProduction,
  banner: {
    js: banner,
  },
}).catch(() => process.exit(1));
